@startuml
left to right direction
skinparam linetype ortho
skinparam roundcorner 6
skinparam entityAttributeIconSize 0

entity "USER" as USER {
  *id : uuid
  --
  active : boolean
  createdAt : datetime
  updatedAt : datetime
  username : string
  email : string
  score : int
  userRole : string
  level : string
  avatar : json
}

entity "GAME" as GAME {
  *id : uuid
  --
  active : boolean
  createdAt : datetime
  updatedAt : datetime
  difficulty : string
}

entity "GAME_SESSION" as GAME_SESSION {
  *id : uuid
  --
  active : boolean
  createdAt : datetime
  updatedAt : datetime
  user_id : uuid
  game_id : uuid
  score : int
  position : int
}

entity "CATEGORY_QUESTION" as CATEGORY_QUESTION {
  *id : uuid
  --
  active : boolean
  createdAt : datetime
  updatedAt : datetime
  level : string
  descriptionCategory : string
  type : string
}

entity "QUESTION" as QUESTION {
  *id : uuid
  --
  active : boolean
  createdAt : datetime
  updatedAt : datetime
  content : json
  moreInfo : text
  category_id : uuid
  timeLimit : int
}

entity "QUESTION_OPTION" as QUESTION_OPTION {
  *id : uuid
  --
  active : boolean
  createdAt : datetime
  updatedAt : datetime
  content : json
  isCorrect : boolean
  question_id : uuid
}

entity "PLAYER_ANSWER" as PLAYER_ANSWER {
  *id : uuid
  --
  active : boolean
  createdAt : datetime
  updatedAt : datetime
  game_session_id : uuid
  question_id : uuid
  selected_option_id : uuid
  isCorrect : boolean
  timeTaken : int
}

entity "GAME_QUESTIONS_QUESTION" as GAME_QUESTIONS_QUESTION {
  *gameId : uuid
  *questionId : uuid
}

USER ||--o{ GAME_SESSION 
GAME ||--o{ GAME_SESSION 

CATEGORY_QUESTION ||--o{ QUESTION 
QUESTION ||--o{ QUESTION_OPTION  

GAME_SESSION ||--o{ PLAYER_ANSWER  
QUESTION ||--o{ PLAYER_ANSWER 
QUESTION_OPTION ||--o{ PLAYER_ANSWER 

GAME ||--o{ GAME_QUESTIONS_QUESTION 
QUESTION ||--o{ GAME_QUESTIONS_QUESTION 

@enduml
